extends Node


var ARTISTS = [
	"Akira Yamaoka",
	"Alexisonfire",
	"Alkaline Trio",
	"American Football",
	"Anais Mitchell",
	"Anamanguchi",
	"Ani DiFranco",
	"Austin Wintory",
	"Auto!Automatic!!",
	"Ayumi Hamasaki",
	"Bear vs. Shark",
	"Big Giant Circles",
	"Blake Robinson",
	"Bloc Party",
	"Bob Nanna",
	"Bone Thugs-N-Harmony",
	"Brad Mehldau",
	"Braid",
	"Brand New",
	"Broken Social Scene",
	"C-jeff",
	"C418",
	"Cap'n Jazz",
	"Chet Atkins",
	"Chipzel",
	"Chromeo",
	"Circa Survive",
	"City and Colour",
	"Clive Caroll",
	"Coda",
	"Common",
	"Controller.Controller",
	"Cursive",
	"Magic Sword",
	"Makoto Matsushita",
	"Marasy8",
	"Seasick Steve",
	"The All-American Rejects",
	"The Anniversary",
	"The Appleseed Cast",
	"The Black Mages",
	"The Books",
	"The City on Film",
	"The Consouls",
	"The Consouls",
	"The Constantines",
	"Tommy Emmanuel",
]

var TITLES = [
	"When You're Gone",
	"Searching The Past",
	"Childish Thoughts",
	"Creeping Distress",
	"Hostility",
	"Snow Driven",
	"Hibernation",
	"Devil's Laughter",
	"Lost Truth",
	"Angel's Scream",
	"Another Warm Body",
	"Forsaken Lullaby",
	"Raw Shock",
	"Lives Wasted Away",
	"Blackest Friday",
	"Endless Depths",
	"Different Persons",
	"Ice",
	"Acceptance",
	"Hell Frozen Rain",
	"Rose Cat",
	"Obsolete",
	"Anumbra",
	"Intro",
	"Title",
	"Light",
	"The Traveller",
	"Home",
	"Technique",
	"Mystery",
	"Ancient Test",
	"Archaic",
	"Fatal",
	"March of the Krotites",
	"Undiscovered Waters",
	"Boss Fraught",
	"Remains",
	"Cathedral",
	"Mithala",
	"The Fall of Mithalas",
	"Heart of the Forest",
	"Hope of Winter",
	"Mother Nature",
	"Druniad Dance",
	"Bright Waters",
	"Above",
	"Moment",
	"Li",
	"Sun Temple",
	"Inevitable",
	"Swim for Your Life",
	"Prometheus",
	"Lost Waters",
	"Arnassi",
	"Dark Places",
	"Gullet",
	"Icy Waters",
	"Sunken City",
	"Mother and Father",
	"The Body",
	"Fallen Breed",
	"Worship",
	"Ending",
	"The Return",
	"Lost to the Waves",
	"The Verse",
	"Fly Away",
	"Fear the Dark",
	"Trailer",
	"Mother's Day",
	"Adventure Time",
	"Misty Morn",
	"Mellow Magnificent",
	"John Waters",
	"Lil Piggy",
	"Snow Problem",
	"This is the Day",
	"Dangerisk",
	"Rumbly Rumble",
	"Mending",
	"Flinging High",
	"Scorch n' Torch",
	"Dark World",
	"City Trial",
	"Power Up",
	"Hatchling Theme",
	"Serris X & Gedo X Boss Theme",
	"Facing the Task",
	"Shortnin' Bread",
	"Hushabye",
	"Flight of the Zinger",
	"Zidane's Theme",
	"Return of the Evil Mist",
	"Lindblum",
	"Lo-Gear Title",
	"Lo-Gear Attract Sounds",
	"Lo-Gear Level 1-1",
	"Lo-Gear End",
	"Pink Bubblegum Man",
	"The Waiting",
	"Land, Sea, and Air",
	"The Waiting (Part 2)",
	"DYFEYW",
	"Sim Whale",
	"Watermaker's",
	"Bone Arrow",
	"Ascension",
	"Season 3 Intro",
	"Wind and Rain",
	"Hospital Corners",
	"Above the Clouds",
	"32k32k",
	"Slumberparty",
	"Tis I, Sir Ronald!",
	"Sugar Cube",
	"The Snake of Greatness",
	"Kindercomp",
	"Spokane",
	"Zenith",
	"Floating Point",
	"Gravity Hill",
	"Law of Cosines",
	"Snipes",
	"AEPOZXLU",
	"GKISTVYN",
	"Mysteries of Udolpho",
	"Garwor",
	"Moire Array",
	"Fill Shippo",
	"Virtua Star Car",
	"Diamonds Never Made a Window",
	"OJ Finds the Real Killers",
	"Trenton Makes, the World Takes",
	"Oh, My Car",
	"Hornebuckle, Who?",
	"Leisure Little Treisure",
	"Romanda",
	"The Truth Is Out There",
	"Doppel & the Gang",
	"Red Leg, Blue Leg",
	"For People of Worlds",
	"The Bear",
	"Tickle Bee",
	"Pocket Parafoil",
	"Titusville TV",
	"Spiker Man Du",
	"Ebu Gogo",
	"The Wheel Bug",
	"MOS Deth",
	"Segway Slater",
	"Hotel Keitel",
	"Century I",
	"Good One, Miosky",
	"Bowman's Tower",
	"Musth",
	"Galdralag",
	"Polycephaly",
	"3 Eyeball Ghost",
	"Voynich Manuscript",
	"Jeannine Christina Delgato",
	"Confuse Mode",
	"Hurricane Hugo",
	"Blast Gaiden",
	"Zilog",
	"Holosseum",
	"UFO Hovercraft",
	"Jazz 2 Intro",
	"Jazz 2 Menu",
	"Beach Bunny!",
	"Carrotus",
	"Pull Back The Bass",
	"Colonius Level 1",
	"Jazz Be Damned",
	"Diamondus Remix",
	"Jazz 2 Bonus Stage",
	"Fast Track",
	"Hippie Heaven",
	"Hell Freezes Over",
	"Jazz Boss Tune 1",
	"Dark Groove (part 1)",
	"Jaz 27",
	"Jaz 30",
	"Frolick Lane",
	"Streetwize",
	"Xmas 2",
	"Jazz Castle",
	"Jungle Fevah V2.0",
	"Labratory Level",
	"Medivo",
	"Tubelectric Remix",
	"Medival Jam",
	"Water Level",
	"White Hare",
	"Finale",
	"Haunted Hare (Secret Boss)",
	"Title",
	"Tutorial",
	"Castle",
	"Funky Foyer",
	"Rocket",
	"Basement",
	"Basement Action",
	"Terrero",
	"Canyon",
	"Green Land",
	"Village",
	"Sun Song",
	"Ashes Of Pigs",
	"The Toll",
	"Asteroid Dance Part 1",
	"Asteroid Dance Part 2",
	"Buy Sell Music",
	"Camanis",
	"Camanise",
	"Deli Shop Quartet",
	"Deli Shop Quartet No 2",
	"Ending Number 1",
	"Ending Number 2",
	"End Of Level",
	"Game Over Solo",
	"Gryphons Of The West",
	"Somebody Pick Up The Gryphone",
	"Gyges, Will You Please Help Me",
	"I Speak Gygese",
	"Halloween Ramble",
	"Tunneling Trolls",
	"Tyrian, The Level",
	"The Musicman",
	"The Navigator",
	"Come Back To Me, Savara",
	"Come Back Again To Savara",
	"Space Journey 1",
	"Space Journey 2",
	"The Final Edge",
	"Starts",
	"Parlance",
]
